PROGETTO APPLICAZIONI WEB - Gestione Agricola/App_Progetto/Controllers/AttuatoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Progetto.Data;
using App_Progetto.Models;
using Humanizer;
using System.Security.Claims;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace App_Progetto.Controllers
{
    [Authorize(Roles = "Agricoltore,Collaboratore")]
    public class AttuatoresController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly ILogger<Controller> _logger;


        public AttuatoresController(UserManager<IdentityUser> userManager, ApplicationDbContext context, ILogger<Controller> logger)
        {
            _context = context;
            _logger = logger;
            _userManager = userManager;
        }

        [Authorize(Roles = "Agricoltore,Collaboratore")]
        public async Task<IActionResult> AttDettaglio(int TerrenoId)
        {
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser != null)
            {
                var gestione = _context.Gestiones
                    .FirstOrDefault(g => g.TerrenoId == TerrenoId && g.UserId == currentUser.Id);

                string ruolo = gestione?.Ruolo ?? "Nessun ruolo associato";

                var query = from a in _context.Attuatores
                            join t in _context.Terrenos on a.TerrenoId equals t.Id
                            where a.TerrenoId == TerrenoId
                            select new
                            {
                                TerrenoId = a.TerrenoId,
                                Mappale = t.Mappale,
                                Foglio = t.Foglio,
                                Id = a.Id,
                                TipoAttuatore = a.TipoAttuatore,
                                Standby = a.Standby,
                                Attivazione = a.Attivazione,
                                Ruolo = ruolo
                            };
                ViewData["IdTerreno"] = TerrenoId;
                var result = await query.ToListAsync();
                foreach (var item in result)
                {
                    Console.WriteLine($"TerrenoId: {item.TerrenoId}, Foglio: {item.Foglio}, Mappale: {item.Mappale}, TipoAttuatore: {item.TipoAttuatore}, Standby: {item.Standby}, Attivazione: {item.Attivazione}");
                }
                return View(result);
            }
            else
            {
                
                return RedirectToAction("Login");
            }
        }

        //[Authorize(Roles = "Agricoltore,Collaboratore")]
        // GET: Attuatores

        public async Task<IActionResult> Index()
        {
            // Ottenere l'ID dell'utente corrente
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var attuatoriUtente = await _context.Attuatores
                .Include(a => a.Terreno)  // Includi il riferimento al Terreno
                .ThenInclude(t => t.Gestiones)  // Assicurati di includere le Gestiones
                .Where(a => a.Terreno.Gestiones.Any(g => g.UserId == userId))
                .ToListAsync(); // Utilizza ToListAsync per eseguire la query in modo asincrono

            return View(attuatoriUtente);
        }

        // GET: Attuatores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Attuatores == null)
            {
                return NotFound();
            }

            var attuatore = await _context.Attuatores
                .Include(a => a.Terreno)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (attuatore == null)
            {
                return NotFound();
            }

            return View(attuatore);
        }

        // GET: Attuatores/Create
        public IActionResult Create(int TerrenoId)
        {
            // Imposta il TerrenoId nella ViewBag (o ovunque tu preferisca passare dati alla vista)
            var terreno = _context.Terrenos.Find(TerrenoId);

            ViewBag.TerrenoId = TerrenoId;
            ViewData["Mappale"] = terreno?.Mappale;
            ViewData["Foglio"] = terreno?.Foglio;

            return View();
        }

        // POST: Attuatores/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TipoAttuatore,Standby,Attivazione,TerrenoId")] Attuatore attuatore)
        {
            _context.Add(attuatore);
            await _context.SaveChangesAsync();
            /*return RedirectToAction(nameof(Index));*/
            //return RedirectToAction("AttDettaglio", new { TerrenoId = attuatore.TerrenoId });
            return RedirectToAction("Create", "Pianoes", new { TerrenoId = attuatore.TerrenoId });
        }

        // GET: Attuatores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Attuatores == null)
            {
                return NotFound();
            }

            var attuatore = await _context.Attuatores.FindAsync(id);
            if (attuatore == null)
            {
                return NotFound();
            }

            var terreno = await _context.Terrenos.FindAsync(attuatore.TerrenoId);

            // Passa TerrenoId e i dati del Terreno alla vista
            ViewData["TerrenoId"] = attuatore.TerrenoId;
            ViewData["Mappale"] = terreno?.Mappale;
            ViewData["Foglio"] = terreno?.Foglio; 
            
            return View(attuatore);
        }

        // POST: Attuatores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Attuatores/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TipoAttuatore,Standby,Attivazione,TerrenoId")] Attuatore attuatore)
        {
            if (id != attuatore.Id)
            {
                return NotFound();
            }
            _context.Update(attuatore);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        // GET: Attuatores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Attuatores == null)
            {
                return NotFound();
            }

            var attuatore = await _context.Attuatores
                .Include(a => a.Terreno)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (attuatore == null)
            {
                return NotFound();
            }

            return View(attuatore);
        }

        // POST: Attuatores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Attuatores == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Attuatores'  is null.");
            }
            var attuatore = await _context.Attuatores.FindAsync(id);
            if (attuatore != null)
            {
                _context.Attuatores.Remove(attuatore);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AttuatoreExists(int id)
        {
          return (_context.Attuatores?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PROGETTO APPLICAZIONI WEB - Gestione Agricola/App_Progetto/Controllers/PianoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Progetto.Data;
using App_Progetto.Models;
using Microsoft.AspNetCore.Authorization;

namespace App_Progetto.Controllers
{
    [Authorize(Roles = "Agricoltore,Collaboratore")]
    public class PianoesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PianoesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pianoes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Pianos.Include(p => p.Attuatores);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Pianoes/Details/5
        public async Task<IActionResult> Details(int? CodAttuatore)
        {
            if (CodAttuatore == null)
            {
                return BadRequest(); // o un altro codice di stato appropriato
            }
            var piano = await _context.Pianos
                .Include(p => p.Attuatores)
                .FirstOrDefaultAsync(p => p.CodAtt == CodAttuatore);

            if(piano == null)
            {
                return RedirectToAction("Create", "Pianoes", new { CodAtt = CodAttuatore});
            }

            var terrenoId = await _context.Attuatores
                .Where(a => a.Id == piano.CodAtt)
                .Select(a => a.TerrenoId)
                .FirstOrDefaultAsync();

            ViewData["CodTerr"] = terrenoId;

            return View(piano);
        }

        // GET: Pianoes/Create
        public IActionResult Create(int CodAtt)
        {
            ViewData["CodAtt"] = CodAtt;

            return View();
        }

        // POST: Pianoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CodicePiano,OrarioAttivazione,OrarioDisattivazione,OrarioAttDefault,OrarioDisattDefault,CondAttivazione,CondDisattivazione,CodAtt")] Piano piano)
        {
            _context.Add(piano);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Pianoes", new { CodAttuatore = piano.CodAtt });

        }

        // GET: Pianoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pianos == null)
            {
                return NotFound();
            }

            var piano = await _context.Pianos.FindAsync(id);
            if (piano == null)
            {
                return NotFound();
            }
            
            ViewData["CodAtt"] = piano.CodAtt;

            return View(piano);
        }

        // POST: Pianoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CodicePiano,OrarioAttivazione,OrarioDisattivazione,OrarioAttDefault,OrarioDisattDefault,CondAttivazione,CondDisattivazione,CodAtt")] Piano piano)
        {
            Console.WriteLine("Ciao: " + piano.CodAtt);
            _context.Update(piano);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", "Pianoes", new { CodAttuatore = piano.CodAtt });

        }

        // GET: Pianoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pianos == null)
            {
                return NotFound();
            }

            var piano = await _context.Pianos
                .Include(p => p.Attuatores)
                .FirstOrDefaultAsync(m => m.CodicePiano == id);
            if (piano == null)
            {
                return NotFound();
            }

            return View(piano);
        }

        // POST: Pianoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pianos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Pianos'  is null.");
            }
            var piano = await _context.Pianos.FindAsync(id);
            if (piano != null)
            {
                _context.Pianos.Remove(piano);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PianoExists(int id)
        {
          return (_context.Pianos?.Any(e => e.CodicePiano == id)).GetValueOrDefault();
        }
    }
}

PROGETTO APPLICAZIONI WEB - Gestione Agricola/App_Progetto/Views/Pianoes/Create.cshtml
@model App_Progetto.Models.Piano

@{
    ViewData["Title"] = "Create";
}

<h1>Crea piano attuatore numero : @ViewData["CodAtt"]</h1>

<h4>Piano</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!-- Ora di Attivazione -->
            <div class="form-group">
                <label asp-for="OrarioAttivazione" class="control-label">Ora di Attivazione</label>
                <input asp-for="OrarioAttivazione" class="form-control" type="time" />
                <span asp-validation-for="OrarioAttivazione" class="text-danger"></span>
            </div>

            <!-- Ora di Disattivazione -->
            <div class="form-group">
                <label asp-for="OrarioDisattivazione" class="control-label">Ora di Disattivazione</label>
                <input asp-for="OrarioDisattivazione" class="form-control" type="time" />
                <span asp-validation-for="OrarioDisattivazione" class="text-danger"></span>
            </div>

            <!-- Orario di Default -->
            <div class="form-group">
                <label asp-for="OrarioAttDefault" class="control-label">Orario di Default</label>
                <input asp-for="OrarioAttDefault" class="form-control" type="time" />
                <span asp-validation-for="OrarioAttDefault" class="text-danger"></span>
            </div>

            <!-- Orario di Disattivazione di Default -->
            <div class="form-group">
                <label asp-for="OrarioDisattDefault" class="control-label">Orario di Disattivazione di Default</label>
                <input asp-for="OrarioDisattDefault" class="form-control" type="time" />
                <span asp-validation-for="OrarioDisattDefault" class="text-danger"></span>
            </div>

            <!-- Altre sezioni del form... -->

            <div class="form-group">
                <label asp-for="CondAttivazione" class="control-label">Condizione di Attivazione</label>
                <input asp-for="CondAttivazione" class="form-control" />
                <span asp-validation-for="CondAttivazione" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CondDisattivazione" class="control-label">Condizione di Disattivazione</label>
                <input asp-for="CondDisattivazione" class="form-control" />
                <span asp-validation-for="CondDisattivazione" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="hidden" id="CodAtt" name="CodAtt" value="@ViewData["CodAtt"]" />  
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

PROGETTO APPLICAZIONI WEB - Gestione Agricola/App_Progetto/Views/Pianoes/Delete.cshtml
@model App_Progetto.Models.Piano

@{
    ViewData["Title"] = "Delete";
}

<h1>Elimina piano attuatore</h1>

<div>
    <h4>Piano</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrarioAttivazione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrarioAttivazione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrarioDisattivazione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrarioDisattivazione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrarioAttDefault)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrarioAttDefault)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrarioDisattDefault)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrarioDisattDefault)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CondAttivazione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CondAttivazione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CondDisattivazione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CondDisattivazione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Attuatores)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Attuatores.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CodicePiano" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PROGETTO APPLICAZIONI WEB - Gestione Agricola/App_Progetto/Views/Pianoes/Details.cshtml
@model App_Progetto.Models.Piano

@{
    ViewData["Title"] = "Details";
}

<h1>Dettagli piano attuatore</h1>

<div>
    <h4>Piano</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrarioAttivazione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrarioAttivazione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrarioDisattivazione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrarioDisattivazione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrarioAttDefault)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrarioAttDefault)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrarioDisattDefault)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrarioDisattDefault)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CondAttivazione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CondAttivazione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CondDisattivazione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CondDisattivazione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Attuatores)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Attuatores.Id)
        </dd>
    </dl>
</div>
<div>
    <a class="btn action-button text-white" asp-controller="Attuatores" asp-action="AttDettaglio" asp-route-TerrenoId="@ViewData["CodTerr"]" style="background-color: dodgerblue">Ritorna indietro</a>
    <a asp-action="Edit" asp-route-id="@Model?.CodicePiano">Edit</a>
</div>

PROGETTO APPLICAZIONI WEB - Gestione Agricola/App_Progetto/Views/Pianoes/Edit.cshtml
@model App_Progetto.Models.Piano

@{
    ViewData["Title"] = "Edit";
}

<h1>Modifica piano numero : @Model.CodicePiano</h1>

<h4>Piano</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CodicePiano" />
            <div class="form-group">
                <label asp-for="OrarioAttivazione" class="control-label"></label>
                <input asp-for="OrarioAttivazione" class="form-control" />
                <span asp-validation-for="OrarioAttivazione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrarioDisattivazione" class="control-label"></label>
                <input asp-for="OrarioDisattivazione" class="form-control" />
                <span asp-validation-for="OrarioDisattivazione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrarioAttDefault" class="control-label"></label>
                <input asp-for="OrarioAttDefault" class="form-control" />
                <span asp-validation-for="OrarioAttDefault" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrarioDisattDefault" class="control-label"></label>
                <input asp-for="OrarioDisattDefault" class="form-control" />
                <span asp-validation-for="OrarioDisattDefault" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CondAttivazione" class="control-label"></label>
                <input asp-for="CondAttivazione" class="form-control" />
                <span asp-validation-for="CondAttivazione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CondDisattivazione" class="control-label"></label>
                <input asp-for="CondDisattivazione" class="form-control" />
                <span asp-validation-for="CondDisattivazione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" id="CodAtt" name="CodAtt" value="@ViewData["CodAtt"]" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

PROGETTO APPLICAZIONI WEB - Gestione Agricola/App_Progetto/Views/Pianoes/Index.cshtml
@model IEnumerable<App_Progetto.Models.Piano>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create">Create un nuovo piano</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrarioAttivazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrarioDisattivazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrarioAttDefault)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrarioDisattDefault)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CondAttivazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CondDisattivazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Attuatores)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrarioAttivazione)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrarioDisattivazione)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrarioAttDefault)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrarioDisattDefault)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CondAttivazione)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CondDisattivazione)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Attuatores.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CodicePiano">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CodicePiano">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CodicePiano">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>